## These functions are written as a solution to Programming Assignement 2 of the R Programming Course.

## makeCacheMatrix creates a special matrix which is really a list containing functions to set the matrix,
## get the matrix, set the inverse matrix, and get the inverse matrix.

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m<<- NULL
  }
  get <- function() x
  setinverse <- function(inverse) m <<- inverse
  getinverse <- function() m
  list (set = set, get = get, setinverse = setinverse, getinverse = getinverse)
}


## cacheSolve checks to see if the inverse of the the matrix generated by makeCacheMatrix already exists.
## It it does, then it pulls out the cached inverse matrix using the getinverse function and lets the 
## user know with a message'getting cached data'. If the inverse does not exist, it calculates and 
## returns the inverse, caching it for the future using the setinverse function.

cacheSolve <- function(x, ...) {
  m <- x$getinverse()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data,...)
  x$setinverse(m)
  m
}
